defmodule Folio.Codegen.Native do
  @moduledoc false

  alias RustQ.Rust

  @native_nifs [
    parse_markdown: [
      args: [markdown: :String],
      returns: "NifResult<Vec<ExContent>>",
      schedule: "DirtyCpu"
    ],
    compile_pdf: [
      args: [
        env: "Env<'a>",
        content: "Vec<ExContent>",
        styles: "Vec<ExStyle>",
        files: "std::collections::HashMap<String, rustler::Binary<'a>>"
      ],
      returns: "NifResult<rustler::Binary<'a>>",
      lifetime: :a,
      schedule: "DirtyCpu"
    ],
    compile_svg: [
      args: [
        content: "Vec<ExContent>",
        styles: "Vec<ExStyle>",
        files: "std::collections::HashMap<String, rustler::Binary<'a>>"
      ],
      returns: "NifResult<Vec<String>>",
      lifetime: :a,
      schedule: "DirtyCpu"
    ],
    compile_png: [
      args: [
        env: "Env<'a>",
        content: "Vec<ExContent>",
        styles: "Vec<ExStyle>",
        files: "std::collections::HashMap<String, rustler::Binary<'a>>",
        dpi: :f64
      ],
      returns: "NifResult<Vec<rustler::Binary<'a>>>",
      lifetime: :a,
      schedule: "DirtyCpu"
    ],
    register_file: [
      args: [path: :String, data: "rustler::Binary<'a>"],
      returns: "rustler::Atom",
      lifetime: :a
    ],
    unregister_file: [
      args: [path: :String],
      returns: "rustler::Atom"
    ]
  ]

  @spec rust_nifs() :: String.t()
  def rust_nifs do
    wrappers = Enum.map(@native_nifs, fn {name, spec} -> wrapper(name, spec) end)

    RustQ.render!(
      "__rq_items!();",
      "generated_nifs.rs",
      preamble: "// This file is generated by RustQ. Do not edit by hand.\n\n",
      splice: [items: wrappers]
    )
  end

  defp wrapper(name, spec) do
    args = Keyword.fetch!(spec, :args)
    call_args = args |> Keyword.keys() |> Enum.map_join(", ", &to_string/1)

    name
    |> Rust.fn(
      args: args,
      returns: Keyword.fetch!(spec, :returns),
      lifetime: Keyword.get(spec, :lifetime),
      body: "#{name}_impl(#{call_args})"
    )
    |> maybe_nif_attr(spec)
  end

  defp maybe_nif_attr(function, spec) do
    case Keyword.get(spec, :schedule) do
      nil -> Rust.attr(function, "rustler::nif")
      schedule -> Rust.attr(function, ~s|rustler::nif(schedule = "#{schedule}")|)
    end
  end
end
