defmodule Folio.Codegen.Native do
  @moduledoc false

  @native_nifs [
    parse_markdown: [
      args: [markdown: :String],
      returns: "NifResult<Vec<ExContent>>",
      schedule: :dirty_cpu
    ],
    compile_pdf: [
      args: [
        env: "Env<'a>",
        content: "Vec<ExContent>",
        styles: "Vec<ExStyle>",
        files: "std::collections::HashMap<String, rustler::Binary<'a>>"
      ],
      returns: "NifResult<rustler::Binary<'a>>",
      lifetime: :a,
      schedule: :dirty_cpu
    ],
    compile_svg: [
      args: [
        content: "Vec<ExContent>",
        styles: "Vec<ExStyle>",
        files: "std::collections::HashMap<String, rustler::Binary<'a>>"
      ],
      returns: "NifResult<Vec<String>>",
      lifetime: :a,
      schedule: :dirty_cpu
    ],
    compile_png: [
      args: [
        env: "Env<'a>",
        content: "Vec<ExContent>",
        styles: "Vec<ExStyle>",
        files: "std::collections::HashMap<String, rustler::Binary<'a>>",
        dpi: :f64
      ],
      returns: "NifResult<Vec<rustler::Binary<'a>>>",
      lifetime: :a,
      schedule: :dirty_cpu
    ],
    register_file: [
      args: [path: :String, data: "rustler::Binary<'a>"],
      returns: "rustler::Atom",
      lifetime: :a
    ],
    unregister_file: [
      args: [path: :String],
      returns: "rustler::Atom"
    ]
  ]

  @spec rust_nifs() :: String.t()
  def rust_nifs do
    wrappers = RustQ.Rustler.nif_exports(@native_nifs)

    RustQ.render!(
      "__rq_items!();",
      "generated_nifs.rs",
      preamble: "// This file is generated by RustQ. Do not edit by hand.\n\n",
      splice: [items: wrappers]
    )
  end
end
