// This file is generated by RustQ. Do not edit by hand.

#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Text"]
pub struct ExText {
    pub text: String,
    pub size: Option<String>,
    pub weight: Option<String>,
    pub fill: Option<String>,
    pub tracking: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Space"]
pub struct ExSpace {}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Heading"]
pub struct ExHeading {
    pub body: Vec<ExContent>,
    pub level: u8,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Paragraph"]
pub struct ExParagraph {
    pub body: Vec<ExContent>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Strong"]
pub struct ExStrong {
    pub body: Vec<ExContent>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Emph"]
pub struct ExEmph {
    pub body: Vec<ExContent>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Strike"]
pub struct ExStrike {
    pub body: Vec<ExContent>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Underline"]
pub struct ExUnderline {
    pub body: Vec<ExContent>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Highlight"]
pub struct ExHighlight {
    pub body: Vec<ExContent>,
    pub fill: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Super"]
pub struct ExSuper {
    pub body: Vec<ExContent>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Sub"]
pub struct ExSub {
    pub body: Vec<ExContent>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Smallcaps"]
pub struct ExSmallcaps {
    pub body: Vec<ExContent>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Image"]
pub struct ExImage {
    pub src: String,
    pub width: Option<String>,
    pub height: Option<String>,
    pub fit: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Table"]
pub struct ExTable {
    pub columns: Option<Vec<String>>,
    pub rows: Option<String>,
    pub children: Vec<ExContent>,
    pub stroke: Option<String>,
    pub gutter: Option<String>,
    pub align: Option<String>,
    pub inset: Option<String>,
    pub fill: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.TableHeader"]
pub struct ExTableHeader {
    pub children: Vec<ExContent>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.TableRow"]
pub struct ExTableRow {
    pub children: Vec<ExContent>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.TableCell"]
pub struct ExTableCell {
    pub body: Vec<ExContent>,
    pub colspan: Option<u32>,
    pub rowspan: Option<u32>,
    pub align: Option<String>,
    pub fill: Option<String>,
    pub stroke: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Math"]
pub struct ExMath {
    pub content: String,
    pub block: bool,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Link"]
pub struct ExLink {
    pub url: String,
    pub body: Vec<ExContent>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Raw"]
pub struct ExRaw {
    pub text: String,
    pub lang: Option<String>,
    pub block: bool,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.List"]
pub struct ExList {
    pub children: Vec<ExContent>,
    pub tight: bool,
    pub marker: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.ListItem"]
pub struct ExListItem {
    pub body: Vec<ExContent>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.EnumList"]
pub struct ExEnum {
    pub children: Vec<ExContent>,
    pub tight: bool,
    pub start: Option<u32>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.EnumItem"]
pub struct ExEnumItem {
    pub body: Vec<ExContent>,
    pub number: Option<u32>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Label"]
pub struct ExLabel {
    pub name: String,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Ref"]
pub struct ExRef {
    pub target: String,
    pub supplement: Option<Vec<ExContent>>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Align"]
pub struct ExAlign {
    pub alignment: String,
    pub body: Vec<ExContent>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Hide"]
pub struct ExHide {
    pub body: Vec<ExContent>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Repeat"]
pub struct ExRepeat {
    pub body: Vec<ExContent>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Place"]
pub struct ExPlace {
    pub alignment: Option<String>,
    pub body: Vec<ExContent>,
    pub float: Option<bool>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.VSpace"]
pub struct ExVSpace {
    pub amount: String,
    pub weak: bool,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.HSpace"]
pub struct ExHSpace {
    pub amount: String,
    pub weak: bool,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Pad"]
pub struct ExPad {
    pub body: Vec<ExContent>,
    pub left: Option<String>,
    pub right: Option<String>,
    pub top: Option<String>,
    pub bottom: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Stack"]
pub struct ExStack {
    pub dir: String,
    pub children: Vec<ExContent>,
    pub spacing: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Block"]
pub struct ExBlock {
    pub body: Vec<ExContent>,
    pub width: Option<String>,
    pub height: Option<String>,
    pub above: Option<String>,
    pub below: Option<String>,
    pub fill: Option<String>,
    pub inset: Option<String>,
    pub radius: Option<String>,
    pub stroke: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Rect"]
pub struct ExRect {
    pub body: Vec<ExContent>,
    pub width: Option<String>,
    pub height: Option<String>,
    pub fill: Option<String>,
    pub inset: Option<String>,
    pub radius: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Square"]
pub struct ExSquare {
    pub body: Vec<ExContent>,
    pub size: Option<String>,
    pub fill: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Circle"]
pub struct ExCircle {
    pub body: Vec<ExContent>,
    pub radius: Option<String>,
    pub fill: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Ellipse"]
pub struct ExEllipse {
    pub body: Vec<ExContent>,
    pub width: Option<String>,
    pub height: Option<String>,
    pub fill: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Line"]
pub struct ExLine {
    pub start: Option<String>,
    pub end: Option<String>,
    pub length: Option<String>,
    pub angle: Option<String>,
    pub stroke: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Polygon"]
pub struct ExPolygon {
    pub vertices: Vec<String>,
    pub fill: Option<String>,
    pub stroke: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Title"]
pub struct ExTitle {
    pub body: Vec<ExContent>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Footnote"]
pub struct ExFootnote {
    pub body: Vec<ExContent>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Colbreak"]
pub struct ExColbreak {
    pub weak: bool,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Pagebreak"]
pub struct ExPagebreak {
    pub weak: bool,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Parbreak"]
pub struct ExParbreak {}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Linebreak"]
pub struct ExLinebreak {}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Divider"]
pub struct ExDivider {}
