// This file is generated by RustQ. Do not edit by hand.

#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Cite"]
#[allow(dead_code)]
pub struct ExRustQCite {
    pub key: String,
    pub supplement: Option<Vec<ExRustQContentSample>>,
    pub form: Option<String>,
    pub style: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Bibliography"]
#[allow(dead_code)]
pub struct ExRustQBibliography {
    pub sources: Vec<String>,
    pub title: Option<Vec<ExRustQContentSample>>,
    pub full: bool,
    pub style: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Figure"]
#[allow(dead_code)]
pub struct ExRustQFigure {
    pub body: Vec<ExRustQContentSample>,
    pub caption: Option<Vec<ExRustQContentSample>>,
    pub placement: Option<String>,
    pub scope: Option<String>,
    pub numbering: Option<String>,
    pub separator: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Quote"]
#[allow(dead_code)]
pub struct ExRustQQuote {
    pub body: Vec<ExRustQContentSample>,
    pub block: bool,
    pub attribution: Option<Vec<ExRustQContentSample>>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Block"]
#[allow(dead_code)]
pub struct ExRustQBlock {
    pub body: Vec<ExRustQContentSample>,
    pub width: Option<String>,
    pub height: Option<String>,
    pub above: Option<String>,
    pub below: Option<String>,
    pub fill: Option<String>,
    pub inset: Option<String>,
    pub radius: Option<String>,
    pub stroke: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Rect"]
#[allow(dead_code)]
pub struct ExRustQRect {
    pub body: Vec<ExRustQContentSample>,
    pub width: Option<String>,
    pub height: Option<String>,
    pub fill: Option<String>,
    pub inset: Option<String>,
    pub radius: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Grid"]
#[allow(dead_code)]
pub struct ExRustQGrid {
    pub columns: Option<Vec<String>>,
    pub rows: Option<Vec<String>>,
    pub gutter: Option<String>,
    pub column_gutter: Option<String>,
    pub row_gutter: Option<String>,
    pub children: Vec<ExRustQContentSample>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.GridCell"]
#[allow(dead_code)]
pub struct ExRustQGridCell {
    pub body: Vec<ExRustQContentSample>,
    pub colspan: Option<u32>,
    pub rowspan: Option<u32>,
    pub align: Option<String>,
    pub fill: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.LocalSet"]
#[allow(dead_code)]
pub struct ExRustQLocalSet {
    pub body: Vec<ExRustQContentSample>,
    pub hyphenate: Option<bool>,
    pub justify: Option<bool>,
    pub first_line_indent: Option<f64>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.RawTypst"]
#[allow(dead_code)]
pub struct ExRustQRawTypst {
    pub source: String,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Sequence"]
#[allow(dead_code)]
pub struct ExRustQSequence {
    pub children: Vec<ExRustQContentSample>,
}
#[derive(Clone, Debug)]
#[allow(dead_code)]
pub enum ExRustQContentSample {
    Cite(ExRustQCite),
    Bibliography(ExRustQBibliography),
    Figure(ExRustQFigure),
    Quote(ExRustQQuote),
    Block(ExRustQBlock),
    Rect(ExRustQRect),
    Grid(ExRustQGrid),
    GridCell(ExRustQGridCell),
    LocalSet(ExRustQLocalSet),
    RawTypst(ExRustQRawTypst),
    Sequence(ExRustQSequence),
}
impl<'a> rustler::Decoder<'a> for ExRustQContentSample {
    fn decode(term: rustler::Term<'a>) -> rustler::NifResult<Self> {
        use rustler::Decoder;
        let env = term.get_env();
        let module: rustler::Atom = term.map_get(atom_struct())?.decode()?;
        let name_str = module.to_term(env).atom_to_string()?;
        match name_str.as_str() {
            "Elixir.Folio.Content.Cite" => {
                Ok(ExRustQContentSample::Cite(Decoder::decode(term)?))
            }
            "Elixir.Folio.Content.Bibliography" => {
                Ok(ExRustQContentSample::Bibliography(Decoder::decode(term)?))
            }
            "Elixir.Folio.Content.Figure" => {
                Ok(ExRustQContentSample::Figure(Decoder::decode(term)?))
            }
            "Elixir.Folio.Content.Quote" => {
                Ok(ExRustQContentSample::Quote(Decoder::decode(term)?))
            }
            "Elixir.Folio.Content.Block" => {
                Ok(ExRustQContentSample::Block(Decoder::decode(term)?))
            }
            "Elixir.Folio.Content.Rect" => {
                Ok(ExRustQContentSample::Rect(Decoder::decode(term)?))
            }
            "Elixir.Folio.Content.Grid" => {
                Ok(ExRustQContentSample::Grid(Decoder::decode(term)?))
            }
            "Elixir.Folio.Content.GridCell" => {
                Ok(ExRustQContentSample::GridCell(Decoder::decode(term)?))
            }
            "Elixir.Folio.Content.LocalSet" => {
                Ok(ExRustQContentSample::LocalSet(Decoder::decode(term)?))
            }
            "Elixir.Folio.Content.RawTypst" => {
                Ok(ExRustQContentSample::RawTypst(Decoder::decode(term)?))
            }
            "Elixir.Folio.Content.Sequence" => {
                Ok(ExRustQContentSample::Sequence(Decoder::decode(term)?))
            }
            _ => Err(rustler::Error::RaiseAtom("unknown_content_variant")),
        }
    }
}
impl rustler::Encoder for ExRustQContentSample {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        match self {
            ExRustQContentSample::Cite(value) => value.encode(env),
            ExRustQContentSample::Bibliography(value) => value.encode(env),
            ExRustQContentSample::Figure(value) => value.encode(env),
            ExRustQContentSample::Quote(value) => value.encode(env),
            ExRustQContentSample::Block(value) => value.encode(env),
            ExRustQContentSample::Rect(value) => value.encode(env),
            ExRustQContentSample::Grid(value) => value.encode(env),
            ExRustQContentSample::GridCell(value) => value.encode(env),
            ExRustQContentSample::LocalSet(value) => value.encode(env),
            ExRustQContentSample::RawTypst(value) => value.encode(env),
            ExRustQContentSample::Sequence(value) => value.encode(env),
        }
    }
}
