// This file is generated by RustQ. Do not edit by hand.

#[rustler::nif(schedule = "DirtyCpu")]
fn parse_markdown(markdown: String) -> NifResult<Vec<ExContent>> {
    parse_markdown_impl(markdown)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn compile_pdf<'a>(
    env: Env<'a>,
    content: Vec<ExContent>,
    styles: Vec<ExStyle>,
    files: std::collections::HashMap<String, rustler::Binary<'a>>,
) -> NifResult<rustler::Binary<'a>> {
    compile_pdf_impl(env, content, styles, files)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn compile_svg<'a>(
    content: Vec<ExContent>,
    styles: Vec<ExStyle>,
    files: std::collections::HashMap<String, rustler::Binary<'a>>,
) -> NifResult<Vec<String>> {
    compile_svg_impl(content, styles, files)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn compile_png<'a>(
    env: Env<'a>,
    content: Vec<ExContent>,
    styles: Vec<ExStyle>,
    files: std::collections::HashMap<String, rustler::Binary<'a>>,
    dpi: f64,
) -> NifResult<Vec<rustler::Binary<'a>>> {
    compile_png_impl(env, content, styles, files, dpi)
}
#[rustler::nif]
fn register_file<'a>(path: String, data: rustler::Binary<'a>) -> rustler::Atom {
    register_file_impl(path, data)
}
#[rustler::nif]
fn unregister_file(path: String) -> rustler::Atom {
    unregister_file_impl(path)
}
