// This file is generated by RustQ. Do not edit by hand.

#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Text"]
#[allow(dead_code)]
pub struct ExRustQText {
    pub text: String,
    pub size: Option<String>,
    pub weight: Option<String>,
    pub fill: Option<String>,
    pub tracking: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Space"]
#[allow(dead_code)]
pub struct ExRustQSpace {}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Heading"]
#[allow(dead_code)]
pub struct ExRustQHeading {
    pub body: Vec<ExRustQContentSample>,
    pub level: u8,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Paragraph"]
#[allow(dead_code)]
pub struct ExRustQParagraph {
    pub body: Vec<ExRustQContentSample>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Strong"]
#[allow(dead_code)]
pub struct ExRustQStrong {
    pub body: Vec<ExRustQContentSample>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.Image"]
#[allow(dead_code)]
pub struct ExRustQImage {
    pub src: String,
    pub width: Option<String>,
    pub height: Option<String>,
    pub fit: Option<String>,
}
#[derive(Clone, Debug, NifStruct)]
#[module = "Folio.Content.TableCell"]
#[allow(dead_code)]
pub struct ExRustQTableCell {
    pub body: Vec<ExRustQContentSample>,
    pub colspan: Option<u32>,
    pub rowspan: Option<u32>,
    pub align: Option<String>,
    pub fill: Option<String>,
    pub stroke: Option<String>,
}
#[derive(Clone, Debug)]
#[allow(dead_code)]
pub enum ExRustQContentSample {
    Text(ExRustQText),
    Space(ExRustQSpace),
    Heading(ExRustQHeading),
    Paragraph(ExRustQParagraph),
    Strong(ExRustQStrong),
    Image(ExRustQImage),
    TableCell(ExRustQTableCell),
}
impl<'a> rustler::Decoder<'a> for ExRustQContentSample {
    fn decode(term: rustler::Term<'a>) -> rustler::NifResult<Self> {
        use rustler::Decoder;
        let env = term.get_env();
        let module: rustler::Atom = term.map_get(atom_struct())?.decode()?;
        let name_str = module.to_term(env).atom_to_string()?;
        match name_str.as_str() {
            "Elixir.Folio.Content.Text" => {
                Ok(ExRustQContentSample::Text(Decoder::decode(term)?))
            }
            "Elixir.Folio.Content.Space" => {
                Ok(ExRustQContentSample::Space(Decoder::decode(term)?))
            }
            "Elixir.Folio.Content.Heading" => {
                Ok(ExRustQContentSample::Heading(Decoder::decode(term)?))
            }
            "Elixir.Folio.Content.Paragraph" => {
                Ok(ExRustQContentSample::Paragraph(Decoder::decode(term)?))
            }
            "Elixir.Folio.Content.Strong" => {
                Ok(ExRustQContentSample::Strong(Decoder::decode(term)?))
            }
            "Elixir.Folio.Content.Image" => {
                Ok(ExRustQContentSample::Image(Decoder::decode(term)?))
            }
            "Elixir.Folio.Content.TableCell" => {
                Ok(ExRustQContentSample::TableCell(Decoder::decode(term)?))
            }
            _ => Err(rustler::Error::RaiseAtom("unknown_content_variant")),
        }
    }
}
impl rustler::Encoder for ExRustQContentSample {
    fn encode<'a>(&self, env: rustler::Env<'a>) -> rustler::Term<'a> {
        match self {
            ExRustQContentSample::Text(value) => value.encode(env),
            ExRustQContentSample::Space(value) => value.encode(env),
            ExRustQContentSample::Heading(value) => value.encode(env),
            ExRustQContentSample::Paragraph(value) => value.encode(env),
            ExRustQContentSample::Strong(value) => value.encode(env),
            ExRustQContentSample::Image(value) => value.encode(env),
            ExRustQContentSample::TableCell(value) => value.encode(env),
        }
    }
}
